DechkoWebApp (1)/DechkoWebApp/DechkoWebApp/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Claims;

using DechkoWebApp.Core.Abstraction;
using DechkoWebApp.Infrastructure.Domain;
using DechkoWebApp.Models.Order;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DechkoWebApp.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IProductService _productService;
        private readonly IOrderService _orderService;

        public OrderController(IProductService productService, IOrderService orderService)
        {
            _productService = productService;
            _orderService = orderService;
        }
        // GET: OrderController
        //Creating list for orders from all users

        [Authorize(Roles = "Administrator")]
        public ActionResult Index()
        {
           
            List<OrderIndexVM> orders = _orderService.GetOrders()
                .Select(x => new OrderIndexVM
                {
                    Id = x.Id,
                    OrderDate = x.OrderDate.ToString("dd-MMM-yyyy hh:mm", CultureInfo.InvariantCulture),
                    UserId = x.UserId,
                    User = x.User.UserName,
                    ProductId = x.ProductId,
                    ProductName = x.Product.Name,
                    Picture = x.Product.Picture,
                    Quantity = x.Quantity,
                    Price = x.Price,
                    Discount = x.Discount,
                    TotalPrice = x.TotalPrice,
                }).ToList();
            return View(orders);
        }


        //Show all made orders from client
        public ActionResult MyOrders()
        {
            string currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            

            List<OrderIndexVM> orders = _orderService.GetOrdersByUserId(currentUserId)
                .Select(x => new OrderIndexVM
                {
                    Id = x.Id,
                    OrderDate = x.OrderDate.ToString("dd-MMM-yyyy hh:mm", CultureInfo.InvariantCulture),
                    UserId = x.UserId,
                    User = x.User.UserName,
                    ProductId = x.ProductId,
                    ProductName = x.Product.Name,
                    Picture = x.Product.Picture,
                    Quantity = x.Quantity,
                    Price = x.Price,
                    Discount = x.Discount,
                    TotalPrice = x.TotalPrice,
                }).ToList();
            return View(orders);
        }
        // GET: OrderController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //For creating and confirm the order
        // GET: OrderController/Create
        public ActionResult Create(int productId, int quantity)
        {
            Product product = _productService.GetProductById(productId);
            if (product == null)
            {
                return NotFound();
            }
            OrderConfirmVM orderForDb = new OrderConfirmVM
            {
                //Id = x.Id,
                ProductId = productId,
                ProductName = product.Name,
                Picture = product.Picture,
                Description = product.Description,
                Quantity = quantity,
                Price = product.Price,
                Discount = product.Discount,
                TotalPrice = quantity * product.Price - quantity * product.Price * product.Discount / 100


            };
            return View(orderForDb);
        }

        // POST: OrderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrderConfirmVM bindingModel)
        {
            if (this.ModelState.IsValid)
            {
                string currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

                var product = this._productService.GetProductById(bindingModel.ProductId);
                if (currentUserId == null || product == null || product.Quantity < bindingModel.Quantity || product.Quantity == 0)
                {
                    return this.RedirectToAction("Index", "Product");
                }

                _orderService.Create(bindingModel.ProductId, currentUserId, bindingModel.Quantity);

                //For successfull order returns to list of products
                return this.RedirectToAction("Index", "Product");
            }
            return this.RedirectToAction("Index", "Product");

        }
    }
}

DechkoWebApp (1)/DechkoWebApp/DechkoWebApp/Controllers/StatisticController.cs
using DechkoWebApp.Core.Abstraction;
using DechkoWebApp.Models.Statistic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DechkoWebApp.Controllers
{
    [Authorize(Roles = "Administrator")]

    public class StatisticController : Controller
    {
        private readonly IStatisticService statisticService;

        public StatisticController(IStatisticService statisticService)
        {
            this.statisticService = statisticService;
        }

        public ActionResult Index()
        {
            StatisticVM statistic = new StatisticVM();

            statistic.CountClients = statisticService.CountClients();
            statistic.CountProducts = statisticService.CountProducts();
            statistic.CountOrders = statisticService.CountOrders();
            statistic.SumOrders = statisticService.SumOrders();

            return View(statistic);
        }
    }
}

DechkoWebApp (1)/DechkoWebApp/DechkoWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DechkoWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/styles.css" />
</head>
<body style="background-color: #ACE2E1;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light nav-fill bg-info border-bottom box-shadow mb-3">
            <div class="container">
                <h5 style="margin:0 auto">Дечко</h5>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Начална страница</a>
                        </li>
                        <li class="nav-item active">
                            <div class="dropdown show">
                                <a class="nav-link active dropdown-toggle" href="#"
                                   id="dropdownMenuLink"
                                   data-toggle="dropdown"
                                   aria-haspopup="true"
                                   aria-expanded="false">
                                    Продукти
                                </a>

                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item" asp-controller="Product" asp-action="Index">Всички продукти</a>
                                    <a class="dropdown-item" href="/Product?SearchStringBrandName=&SearchStringCategoryName=Кукли">Кукли</a>
                                    <a class="dropdown-item" href="/Product?SearchStringBrandName=&SearchStringCategoryName=Конструктори">Конструктори</a>
                                    <a class="dropdown-item" href="/Product?SearchStringBrandName=&SearchStringCategoryName=Плюшени+играчки">Плюшени играчки</a>
                                    <a class="dropdown-item" href="/Product?SearchStringBrandName=&SearchStringCategoryName=Бебешки+играчки">Бебешки играчки</a>
                                    <a class="dropdown-item" href="/Product?SearchStringBrandName=&SearchStringCategoryName=Интерактивни+играчки">Интерактивни играчки</a>
                                    <a class="dropdown-item" href="/Product?SearchStringBrandName=&SearchStringCategoryName=Настолни+игри">Настолни игри</a>
                                    <a class="dropdown-item" href="/Product?SearchStringBrandName=&SearchStringCategoryName=Коли">Коли</a>
                                    <a class="dropdown-item" href="/Product?SearchStringBrandName=&SearchStringCategoryName=Топки">Топки</a>






                                </div>
                            </div>
                        </li>
                        @if ((this.User.Identity.IsAuthenticated) && (this.User.IsInRole("Client") || (this.User.IsInRole("Administrator"))))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="MyOrders">Моите поръчки</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contacts">Контакти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Поверителност</a>
                        </li>
                        @if ((this.User.Identity.IsAuthenticated) && (this.User.IsInRole("Administrator")))
                        {
                            <li class="nav-item active">
                                <div class="dropdown show">
                                    <a class="nav-link active dropdown-toggle" href="#"
                                       id="dropdownMenuLink"
                                       data-toggle="dropdown"
                                       aria-haspopup="true"
                                       aria-expanded="false">
                                        Статистически модул
                                    </a>

                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        <a class="dropdown-item" asp-controller="Client" asp-action="Index">Клиенти</a>
                                        <a class="dropdown-item" asp-controller="Statistic" asp-action="Index">Статистика</a>
                                        <a class="dropdown-item" asp-controller="Order" asp-action="Index">Поръчки</a>
                                    </div>
                                </div>
                            </li>

                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Дечко <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>