DechkoWebApp (1)/DechkoWebApp/DechkoWebApp/Models/Client/ClientDeleteVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DechkoWebApp.Models.Client
{
    public class ClientDeleteVM 
    {
        public string Id { get; set; }

        [Display(Name = "Потребителско име")]
        public string UserName { get; set; }

        [Display(Name = "Име")]
        public string FirstName { get; set; }

        [Display(Name = "Фамилия")]
        public string LastName { get; set; }

        [Display(Name = "Адрес")]
        public string Address { get; set; }

        [Display(Name = "Имейл")]
        public string Email { get; set; }



    }    
}

DechkoWebApp (1)/DechkoWebApp/DechkoWebApp/Models/Client/ClientIndexVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DechkoWebApp.Models.Client
{
    public class ClientIndexVM
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public bool IsAdmin { get; set; }
    }
}

DechkoWebApp (1)/DechkoWebApp/DechkoWebApp/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using DechkoWebApp.Infrastructure.Domain;
using DechkoWebApp.Models.Client;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DechkoWebApp.Controllers
{
    
    public class ClientController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;

        public ClientController(UserManager<ApplicationUser> userManager)
        {
            this.userManager = userManager;
        }


        // GET: ClientController
        public async Task<ActionResult> Index()
        {
            var allUsers = this.userManager.Users
                .Select(u => new ClientIndexVM
                {
                    Id = u.Id,
                    UserName = u.UserName,
                    FirstName = u.FirstName,
                    LastName = u.LastName,
                    Address = u.Address,
                    Email = u.Email,
                })
                .ToList();
            var adminIds = (await this.userManager.GetUsersInRoleAsync("Administrator"))
                .Select(a => a.Id).ToList();
            foreach (var user in allUsers)
            {
                user.IsAdmin = adminIds.Contains(user.Id);
            }

            var users = allUsers.Where(x => x.IsAdmin == false)
                .OrderBy(x => x.UserName).ToList();

            return this.View(users);

        }
       

        // GET: ClientDeleteVM/Delete/5
        public ActionResult Delete(string id)
        {
            var user = this.userManager.Users.FirstOrDefault(x => x.Id == id);

            if (user == null)
            {
                return NotFound();
            }
            ClientDeleteVM userToDelete = new ClientDeleteVM()
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Address = user.Address,
                Email = user.Email,
                UserName = user.UserName
            };
            return View(userToDelete);
        }

        // POST: ClientDeleteVM/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(ClientDeleteVM bingingModel)
        {
            string id = bingingModel.Id;
            var user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            else
            {
                IdentityResult result = await userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("SuccessDeleteUser");
                }
                else
                {
                    return NotFound();
                }
            }
        }
        public ActionResult SuccessDeleteUser()
        {
            return View();
        }
        
    }
}

DechkoWebApp (1)/DechkoWebApp/DechkoWebApp/Views/Client/Delete.cshtml
@model DechkoWebApp.Models.Client.ClientDeleteVM

@{
    ViewData["Title"] = "Delete";
}

<h1>Изтриване на потребители</h1>

<h3>Сигурни ли сте,че искате да изтриете потребител?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Изтрий" class="btn btn-danger" /> |
        <a asp-action="Index">Към всички потребители</a>

    </form>
</div>

DechkoWebApp (1)/DechkoWebApp/DechkoWebApp/Views/Client/Index.cshtml
@model IEnumerable<DechkoWebApp.Models.Client.ClientIndexVM>

@{
    ViewData["Title"] = "Index";
}

<h1>Клиенти</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                Потребителско име
            </th>
            <th>
               Име
            </th>
            <th>
               Фамилия
            </th>
            <th>
               Адрес
            </th>
            <th>
               Имейл
            </th>
           
           
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsAdmin)
            </td>
            <td>
               
                <a asp-action="Delete" asp-route-id="@item.Id">Изтрий</a>
            </td>
        </tr>
}
    </tbody>
</table>

DechkoWebApp (1)/DechkoWebApp/DechkoWebApp/Views/Client/SuccessDeleteUser.cshtml
<h1>Успешно изтрихте потребител!</h1>
<a asp-controller="Client" asp-action="Index">Към всички потребители</a>